flask_app/movies/routes.py
import base64, io
from io import BytesIO
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user, login_required

from .. import movie_client
from ..forms import MovieReviewForm, SearchForm, SongRatingForm, SongLikeForm
from ..models import User, Review
from ..utils import current_time

movies = Blueprint("movies", __name__)
""" ************ Helper for pictures uses username to get their profile picture************ """


def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image


""" ************ View functions ************ """


@movies.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("movies.query_results", query=form.search_query.data))

    return render_template("index.html", form=form)


@movies.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = movie_client.search(query)
    except ValueError as e:
        return render_template("query.html", error_msg=str(e))

    return render_template("query.html", results=results)


# NICO: Song rating route
@movies.route("/rate/<movie_id>", methods=["POST"])
@login_required
def rate_song(movie_id):
    try:
        result = movie_client.get_album_by_id(movie_id)
    except ValueError as e:
        return render_template("song_comments.html", error_msg=str(e))
    rating_form = SongRatingForm()
    comment_form = MovieReviewForm()
    
    if rating_form.validate_on_submit():
        rating_value = int(rating_form.rating.data)
        review = Review(
            commenter=current_user._get_current_object(),
            content=f"Rated {rating_value} stars.",
            date=current_time(),
            imdb_id=movie_id,
            movie_title=result.name,
            rating=rating_value,
        )
        review.save()
        flash("Thank you for rating the song!", "success")
        return redirect(url_for("movies.movie_detail", movie_id=movie_id))

    flash("Please select a valid rating before submitting.", "error")
    return redirect(url_for("movies.index", movie_id=movie_id))

# SHAD: Song like route:
@movies.route("/like/<movie_id>", methods=["POST"])
@login_required
def like_song(movie_id):
    try:
        # Retrieve the movie by ID
        result = movie_client.get_album_by_id(movie_id)
    except ValueError as e:
        return render_template("song_comments.html", error_msg=str(e))

    like_form = SongLikeForm()

    # Debug form validation
    if like_form.validate_on_submit():
        print("Form validated!")
        # Get the like choice (1 means liked)
        like_choice = int(like_form.like.data)

        # Save the "Liked!" comment
        liked_comment = Review(
            like=like_choice,
            commenter=current_user._get_current_object(),
            content="Liked!",
            date=current_time(),
            imdb_id=movie_id,
            movie_title=result.name,
        )
        liked_comment.save()
        print("Liked comment saved: ", liked_comment.content)

        flash("Thank you for liking the song!", "success")
        return redirect(url_for("movies.movie_detail", movie_id=movie_id))
    else:
        print("Form validation failed:", like_form.errors)

    flash("An error occurred while processing your like.", "error")
    return redirect(url_for("movies.index"))




# NICO: Song comments route
@movies.route("/movies/<movie_id>", methods=["GET", "POST"])
def movie_detail(movie_id):
    try:
        result = movie_client.get_album_by_id(movie_id)
    except ValueError as e:
        return render_template("song_comments.html", error_msg=str(e))

    rating_form = SongRatingForm()
    like_form = SongLikeForm()
    comment_form = MovieReviewForm()
    if comment_form.validate_on_submit():
        comment = Review(
            commenter=current_user._get_current_object(),
            content=comment_form.text.data,
            date=current_time(),
            imdb_id=movie_id,
            movie_title=result.name,
        )
        comment.save()
        return redirect(request.path)

    comments = Review.objects(imdb_id=movie_id)

    return render_template(
        "song_comments.html",
        rating_form=rating_form,
        like_form=like_form,
        comment_form=comment_form,
        movie=result,
        reviews=comments,
    )



@movies.route("/user/<username>")
def user_detail(username):
    # uncomment to get review image
    # user = find first match in db
    # img = get_b64_img(user.username) use their username for helper function
    return "user_detail"

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
import io
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import (
    RegistrationForm,
    LoginForm,
    UpdateUsernameForm,
    UpdateProfilePicForm,
)
from ..models import User, Review


users = Blueprint("users", __name__)

""" ************ User Management views ************ """


# TODO: implement
@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        user.save()
        return redirect(url_for("users.login"))

    return render_template("register.html", form=form)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    # if current_user.is_authenticated:
    # return redirect(url_for('movies.index'))

    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password.", "danger")

    return render_template("login.html", form=form)


# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("movies.index"))


@users.route("/user/<username>")
@login_required
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)
    
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return render_template(
        "user_detail.html", user=user, reviews=reviews, error=None, image=image
    )


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    reviews = Review.objects(user=current_user)
    profile_pic = None
    if current_user.profile_pic.get() is not None:
        bytes_im = BytesIO(current_user.profile_pic.read())
        profile_pic = base64.b64encode(bytes_im.getvalue()).decode()

    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            new_name = update_username_form.username.data
            existing_user = User.objects(username=new_name).first()

            if existing_user:
                flash("Username is taken, choose another username", "danger")
            else:
                current_user.modify(username=new_name)
                current_user.save()
                flash("Your username is updated!", "success")
                return redirect(url_for("users.account"))


        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            pic_file = update_profile_pic_form.picture.data
            filename = secure_filename(pic_file.filename)
            content_type = f'image/{filename.split(".")[-1]}'


            if current_user.profile_pic.get() is None:
                current_user.profile_pic.put(pic_file.stream, content_type=content_type)
            else:
                current_user.profile_pic.replace(pic_file.stream, content_type=content_type)
                
            current_user.save()  
            flash("picture updated!", "success")
           
            if current_user.profile_pic.get() is not None:

                bytes_im = BytesIO(current_user.profile_pic.read())
                profile_pic = base64.b64encode(bytes_im.getvalue()).decode()
                return redirect(url_for("users.account"))
        
        # TODO: handle get requests
    return render_template(
        "account.html",
        update_username_form= update_username_form,
        update_profile_pic_form= update_profile_pic_form,
        user= current_user,
        image = profile_pic,
        reviews = reviews
    )

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if image %}
        {# Profile picture #}
        <img class="rounded-2xl h-24 w-24" src="data:image/png;base64,{{image}}" alt="image">
    {% endif %}

    {# TODO: Greeting (must include the current user's username) #}
    <h2 class="text-4xl font-bold opacity-50 my-4">Welcome, {{ user.username }}!</h2>

</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Username
    </h3>
    <form class="review-form" method="POST" action="">
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username.label }}
            {{ update_username_form.username(class="form-content") }}
            {% if update_username_form.username.errors %}
            <div class="error" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl">
        Update Profile Picture
    </h3>
    <form class="review-form" method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label }}
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="error" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<div class="flex justify-center">
    {# TODO: Link to see all of the current user's reviews. #}
    <a class="review-button" href="{{ url_for('movies.user_detail', username=user.username) }}">All Reviews</a>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='compiled.css')}}"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"
    />
   

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Music App</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('movies.index') }}">
        <span class="hidden sm:block">Home</span>
        <span class="block sm:hidden">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink text-white" href="{{ url_for('users.account') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink text-white"
        style="background-color: #DB5C68; color: white; text-decoration: none;"
        onmouseover="this.style.backgroundColor='#C14E5A'; this.style.color='white';"
        onmouseout="this.style.backgroundColor='#DB5C68'; this.style.color='white';"
        href="{{ url_for('users.logout') }}">Logout</a>

         </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register') }}">Register</a>
    </div>
    {% endif %}
</nav>
{% block content %}{% endblock %}{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %} {% block content %}
<div class="main-container">
  <div class="decoration-main-container"><div class="decoration-main"></div></div>
  <h2 class="main-title"> Waves </h2>
  <form class="searchbar" action="/" method="POST">
    {{ form.csrf_token }}
    {{ form.search_query(class="form-control", placeholder="Search") }}
    
    {% if form.search_query.errors %}
      <div class="error" role="alert">
        {% for error in form.search_query.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% endif %}
    
    {{ form.submit(class="form-button") }}
  </form>

  

</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

flask_app/templates/query.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

<div class="results-container">
  <div class="decoration-container"><div class="decoration"></div></div>
  {% for result in results %}
  <a 
    href="{{ url_for('movies.movie_detail', movie_id=result.id) }}"
    class="group movie-card"
  >
    <img src="{{ result.image }}" class="movie-card-img" alt="missing" />
    <h5 class="movie-card-content"> {{ result.title }}
      <span class="text-neutral-400 font-normal"> &middot; {{ result.release_date }} </span>
    </h5>
  </a>
  {% endfor %}
</div>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Registration</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-200 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>
<!-- Registration Form: -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="error" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="error" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>

{% endblock %}

flask_app/templates/song_comments.html
{% extends "header.html" %}
{% block content %}

<div class="movie-container">
  {# Display movie details #}
  <ul class="movie-info">
    <div class="movie-title"> {{ movie.name }}
      <p class="movie-date"> &middot; {{ movie.release_date }}</p>
    </div>
    <img class="movie-img" alt="alt text" src="{{ movie.image }}" />
    <li class="opacity-40 md:px-4"><b>Artist:</b> {{ movie.artists | join(", ") }}</li>
    <li class="opacity-40 md:px-4"><b>Genres:</b> {{ movie.genres | join(", ") }}</li>
    <li class="opacity-40 md:px-4"><b>Producers:</b> {{ "UNAVAILABLE" }}</li>
  </ul>

  {# Comments Section #}
  <div class="reviews">
    <h1 class="reviews-title"> Comments
      <small class="reviews-count"> {{ reviews | length }} comments </small>
    </h1>
    <ul class="review-container">
      {% for review in reviews %}
        <li class="review flex gap-2">
          <img class="h-20 w-20 rounded-lg" src="data:image/png;base64,{{review.image}}" alt="User profile" />
          <div class="w-full">
            <span class="review-date">{{ review.date }}</span>
            <a class="review-commenter" href="{{ url_for('movies.user_detail', username=review.commenter.username) }}">
              @{{ review.commenter.username }}
            </a>
            <p class="review-content">{{ review.content }}</p>
          </div>
        </li>
      {% endfor %}
    </ul>

    {% if current_user.is_authenticated %}
      {# Comment input form #}
      <div class="container mx-auto">
        <form method="POST" action="" class="review-form">
          {{ comment_form.csrf_token }}
          <div class="form-group review-input">
            {{ comment_form.text.label }} 
            {{ comment_form.text(class="form-content", placeholder="Add a comment about the song...", id="comment-textarea") }}
            {% if comment_form.text.errors %}
              <div class="error" role="alert">
                {% for error in comment_form.text.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          {{ comment_form.submit(class="review-button mt-4") }}
        </form>        
      </div>
    {% endif %}
  </div>

  <div class="w-0 lg:w-96">
    <h3 class="text-xl font-bold mb-4">Rate This Song</h3>
    <form method="POST" action="{{ url_for('movies.rate_song', movie_id=movie.id) }}">
        {{ rating_form.csrf_token }}
        <div class="star-rating">
          {% for subfield in rating_form.rating %}
              <input type="radio" id="{{ subfield.id }}" name="{{ subfield.name }}" value="{{ subfield.data }}" class="star-input">
              <label for="{{ subfield.id }}" class="cursor-pointer text-2xl text-gray-400 hover:text-yellow-500 transition duration-200">
                  ★
              </label>
          {% endfor %}
      </div>
        

        {{ rating_form.submit(class="review-button mt-4") }}
    </form>

    {% if rating_form.errors %}
        <div class="error" role="alert">
            <ul>
                {% for field, errors in rating_form.errors.items() %}
                    {% for error in errors %}
                        <li>{{ field }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <div class="social-share">
      <h3 class="text-xl font-bold mb-4">Share</h3>
      <button class="share-button">Share on Twitter</button>
      <button class="share-button">Share on Instagram</button>
      <button class="share-button">Share on Facebook</button>
    </div>

    {# Heart Button for Likes#}
<div class="heart-button-container mt-4">
    <form method="POST" action="{{ url_for('movies.like_song', movie_id=movie.id) }}">
      {{ like_form.csrf_token }}
      <input type="hidden" name="like" value="1"> 
      <button type="submit" class="heart-button large-button spaced-button">
          ❤️ <!--Once liked cannot be taken back" -->
      </button>
  </form>
</div>

    
    <div class="cool-emoji">
      <span style="--i:1;">C</span>
      <span style="--i:2;">o</span>
      <span style="--i:3;">m</span>
      <span style="--i:4;">i</span>
      <span style="--i:5;">n</span>
      <span style="--i:6;">g &nbsp</span>
      <span style="--i:7;">S</span>
      <span style="--i:8;">o</span>
      <span style="--i:9;">o</span>
      <span style="--i:10;">n</span>
      <span style="--i:11;">😎</span>
    </div>
  
  </div>
</div>

<script>
  document.getElementById("comment-textarea").addEventListener("keydown", function (e) {
    if (e.key === "Enter" && !e.shiftKey) { 
      e.preventDefault(); 
      document.getElementById("post-comment-btn").click(); 
    }
  });
</script>

{% endblock content %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
{% if error %}
    <b class="text-red-400" role="alert">
        {{ error }}
    </b>
{% endif %}


<style>
    /* table style */
    .table-custom {
        width: 100%;
        border-collapse: collapse;
        font-family: Arial, sans-serif;
        font-size: 1rem;
        margin: 1rem 0;
        color: #333;
        box-shadow: 0 4px 8px rgb(15, 184, 145);
    }
    
    .table-custom thead {
        background-color: rgb(16, 184, 145);
        color: #fff;
        text-align: left;
    }
    
    .table-custom thead th {
        padding: 12px 15px;
        font-weight: bold;
    }
    
    .table-custom tbody tr:nth-child(even) {
        background-color: rgb(16, 184, 145);
    }
    
    .table-custom tbody tr:hover {
        background-color: #f1f1f1;
    }
    
    .table-custom tbody td {
        padding: 10px 15px;
    }
    
    .table-custom {
        border-radius: 8px;
        overflow: hidden;
    }
</style>



<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {# User's Profile Picture #}
    <img class="rounded-2xl" src="data:image/png;base64,{{image}}" alt="image">
    {# TODO: Indicate which user's reviews we're looking at #}
    <h2 class="text-4xl font-bold opacity-50 my-4">{{ user.username }}'s comments</h2>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h4 class="text-2xl text-neutral-500">Number of Comments: 
        <b class="text-white">{{ reviews.count() }}</b>
    </h4>
    <table class="table-custom">
        <thead class="bg-gray-700 text-white">
                <tr>
                    <th style="border: 1px solid #fff4">Date</th>
                    <th style="border: 1px solid #fff4">Artist</th>
                    <th style="border: 1px solid #fff4">Comment</th>
                    
                </tr>

        </thead>
        <tbody>
            {% for review in reviews %}
                {% if review.content and review.rating is none and not review.content=="Liked!"%}
                <tr>
                    <td style="border: 1px solid #fff4">{{ review.date }}</td>
                    <td style="border: 1px solid #fff4">{{ review.movie_title }}</td>
                    <td style="border: 1px solid #fff4">{{ review.content }}</td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>


<!-- Liked Songs Table -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 mt-6">
    <h4 class="text-2xl text-neutral-500">Liked Songs: </h4>
    <table class="table-custom">
        <thead class="thead-dark">
            <tr>
                <th style="border: 1px solid #fff4">Date</th>
                <th style="border: 1px solid #fff4">Movie Title</th>
            </tr>
        </thead>
        <tbody>
            {% for review in reviews %}
                {% if review.like > 0 and review.content=="Liked!" %}
                <tr class="hover:bg-gray-100 border-b">
                    <td style="border: 1px solid #fff4">{{ review.date }}</td>
                    <td style="border: 1px solid #fff4">{{ review.movie_title }}</td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- New Table for Ratings -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 mt-6">
    <h4 class="text-2xl text-neutral-500">Ratings: </h4>
    <table class="table-custom">
    <thead class="thead-dark">
        <tr>
            <th>Date</th>
            <th>Title</th>
  
            <th>Rating</th>
        </tr>
    </thead>
    <tbody>
        {% for review in reviews %}
            {%if review.rating is not none and review.rating > 0 %}
                <tr>
                    <td>{{ review.date }}</td>
                    <td>{{ review.movie_title }}</td>
                    <td>
                        {% if review.rating %}
                            {% for _ in range(review.rating) %}
                                ⭐
                            {% endfor %}
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>

</div>

{% endblock %}